function Codeur = importCodeur(filename, dataLines)
%IMPORTFILE Import data from a text file
%  CODEURA = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  CODEURA = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  CodeurA = importfile("D:\PFE\Test\Test0721\Recording 17-14-40 21.7.2020\CodeurA.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 21-Jul-2020 17:59:10

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time", "dist"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Codeur = readtable(filename, opts);

end